github.com:
    users:
        seredomi:
            oauth_token: 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
    git_protocol: https
    user: seredomi
    oauth_token: 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
